#!/bin/bash

# Install coursier
curl -L -o coursier https://git.io/coursier-cli
chmod +x coursier

# Install almond for Scala 2.12
SCALA_VERSION=2.13.3 ALMOND_VERSION=0.10.6
./coursier bootstrap \
  -r jitpack \
  -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
  sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
  -o almond
#  --sources --default=true \
#  -o almond
./almond --install \
  --command "java -XX:MaxRAMPercentage=80.0 -jar almond" \
  --copy-launcher true
rm -f almond

jupyter contrib nbextension install --user
jupyter nbextension enable exercise2/main


# Install required Jupyter/JupyterLab extensions
# jupyter labextension install @jupyterlab/plotly-extension

# Set indentation to two spaces
JUPYTER_CONFIG_DIR=$(jupyter --config-dir)

# Classic notebook
mkdir -p $JUPYTER_CONFIG_DIR/nbconfig/
cat > $JUPYTER_CONFIG_DIR/nbconfig/notebook.json <<- EOF
{
  "CodeCell": {
    "cm_config": {
      "indentUnit": 2
    }
  },
  "load_extensions": {
    "exercise2/main": true
  }
}
EOF

# JupyterLab notebook
mkdir -p $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/notebook-extension/
cat > $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings <<- EOF
{
    "codeCellConfig": {
      "tabSize": 2
    }
}
EOF

# JupyterLab editor
mkdir -p $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/fileeditor-extension/
cat > $JUPYTER_CONFIG_DIR/lab/user-settings/@jupyterlab/fileeditor-extension/plugin.jupyterlab-settings <<- EOF
{
    "editorConfig": {
      "tabSize": 2,
    }
}
EOF

# Installing IHaskell Kernel
cd
if [ ! -d $HOME/bin ]
then
    mkdir $HOME/bin
fi
export PATH=$PATH:$HOME/bin:$HOME/.local/bin
curl -sSL https://get.haskellstack.org/ | sh -s - -d $HOME/bin
git clone https://github.com/gibiansky/IHaskell
pushd IHaskell
pip3 install -r requirements.txt
# stack install gtk2hs-buildtools # Disabled for now because gtk2hs-buildtools doesn't work with lts-13 yet
echo "stack install --fast"
stack install --fast
ihaskell install --stack
popd
