#!/bin/bash

shiftFirstParameter() {
    shift
    local result="$*"
    echo "$result"
}

conda activate /srv/conda/envs/notebook

export PATH=$PATH:$HOME/bin:$HOME/.local/bin

args=$(shiftFirstParameter "$@")

exec stack exec jupyter-notebook -- "$args"
