#!/bin/bash

conda activate /srv/conda/envs/notebook

export PATH=$PATH:$HOME/bin:$HOME/.local/bin

echo "Command: $@"
d=$(date)
echo "Date: $d"

shift

echo "Arguments: $@"

exec $HOME/bin/stack exec jupyter-notebook -- "$@"
