#!/bin/bash

conda activate /srv/conda/envs/notebook

export PATH=$PATH:$HOME/bin:$HOME/.local/bin

echo "Command: $@"

shift

echo "Arguments: $@"

exec $HOME/bin/stack exec jupyter-notebook -- "$@"
